刷怪笼:
  普通刷怪笼:
    name: "普通刷怪笼"
    lore:
      - "品质：普通"
      - "耐久：<var:耐久>"
    # 随机耐久 50~100
    耐久: "50~100"
    刷怪笼类型:
      # 随机一种动物，权重为 10
      - "Animals:10"
  高级牛刷怪笼:
    name: "牛刷怪笼"
    lore:
      - "品质：普通"
      - "耐久：<var:耐久>"
    耐久: "100~200"
    类型: "COW"

debug: true