刷怪笼:
  普通刷怪笼:
    name: "普通刷怪笼"
    lore:
      - "品质：普通"
      - "刷怪次数：<var:刷怪次数>"
      - "类型：<var:类型>"
    # 随机刷怪次数 50~100
    刷怪次数: "50~100"
    刷怪笼类型:
      # 随机一种动物，权重为 10
      - "Animals:10"
  高级牛刷怪笼:
    name: "牛刷怪笼"
    lore:
      - "品质：普通"
      - "刷怪次数：<var:刷怪次数>"
    刷怪次数: "100~200"
    类型: "COW"

debug: true

data:
  storage-method: h2