刷怪笼:
  动物刷怪笼:
    name: "<gold><bold>动物刷怪笼"
    lore:
      - "<aqua>类型：<yellow><var:type>"
      - "<aqua>刷怪次数：<yellow><var:totalCount>"
      - "<aqua>最小刷怪间隔：<yellow><var:minSpawnDelay>"
      - "<aqua>最大刷怪间隔：<yellow><var:maxSpawnDelay>"
      - "<aqua>生成数量：<yellow><var:spawnCount>"
      - "<aqua>最大数量：<yellow><var:maxNearbyEntities>"
      - "<aqua>激活范围：<yellow><var:requiredPlayerRange>"
      - "<aqua>生成范围：<yellow><var:spawnRange>"
    # 随机刷怪次数 50~100
    totalCount: "50~100"
    # 在最大和最小刷怪间隔中随机一个数值作为下次刷怪间隔
    # 20tick 为 1 秒， 200tick 为 10 秒
    minSpawnDelay: 200
    maxSpawnDelay: 800
    # 每次尝试生成 4 个生物
    spawnCount: 4
    # 设置允许在生成范围内的这个生成器附近的相似实体的最大数量
    maxNearbyEntities: 16
    # 玩家激活范围，玩家在什么范围内能够激活刷怪笼，设为0将始终激活
    requiredPlayerRange: 16
    # 设置刷怪笼的生物半径
    spawnRange: 4
    # 根据权重来随机获取一个刷怪笼类型
    type:
      # 所有动物的权重为 10
      - "Animals:10"
      # 猫的权重为 0，不会产生猫
      - "Cat:0"
  怪物刷怪笼:
    name: "<gold><bold>怪物刷怪笼"
    lore:
      - "<aqua>类型：<yellow><var:type>"
      - "<aqua>刷怪次数：<yellow><var:totalCount>"
      - "<aqua>最小刷怪间隔：<yellow><var:minSpawnDelay>"
      - "<aqua>最大刷怪间隔：<yellow><var:maxSpawnDelay>"
      - "<aqua>生成数量：<yellow><var:spawnCount>"
      - "<aqua>最大数量：<yellow><var:maxNearbyEntities>"
      - "<aqua>激活范围：<yellow><var:requiredPlayerRange>"
      - "<aqua>生成范围：<yellow><var:spawnRange>"
    totalCount: "50~100"
    minSpawnDelay: 200
    maxSpawnDelay: 800
    spawnCount: 4
    maxNearbyEntities: 16
    requiredPlayerRange: 16
    spawnRange: 4
    type:
      - "Monster:10"
data:
  storage-method: h2

# 刷怪笼增幅器，可自定义新增更多的增幅器
booster-item:
  简易增幅器:
    type: "GOLD_NUGGET"
    name: "<gold><bold>刷怪次数增加器"
    lore:
      - "<aqua>刷怪次数 <yellow><var:totalCount>"
      - "<aqua>最小刷怪间隔 <yellow><var:minSpawnDelay>"
      - "<aqua>最大刷怪间隔 <yellow><var:maxSpawnDelay>"
      - "<aqua>生成数量 <yellow><var:spawnCount>"
      - "<aqua>最大数量 <yellow><var:maxNearbyEntities>"
      - "<aqua>激活范围 <yellow><var:requiredPlayerRange>"
      - "<aqua>生成范围 <yellow><var:spawnRange>"
    # 刷怪总数 +50
    totalCount: 50
    # 最小刷怪间隔 -100
    minSpawnDelay: -100
    # 最大刷怪间隔 -100
    maxSpawnDelay: -100
    # 刷怪数 +1
    spawnCount: 1
    # 相似实体最大数量 +1
    maxNearbyEntities: 1
    # 激活距离 +1
    requiredPlayerRange: 1
    # 半径 -1
    spawnRange: -1
  # 可增加更多增幅器配置，在下面新增即可