刷怪笼:
  普通刷怪笼:
    name: "普通刷怪笼"
    lore:
      - "品质：普通"
      - "耐久：<var:耐久>"
    # 随机耐久 50~100
    耐久: "50~100"
    刷怪笼类型:
      # 随机一种动物，权重为 10
      - "ANIMAL:10"
      # 随机一种怪物，权重为 20
      - "MONSTER:20"
      # 末影龙与凋零BOSS的权重为 0
      - "BOSS:0"
      # 牛的刷怪笼权重为 40
      - "COW:40"
  高级牛刷怪笼:
    name: "牛刷怪笼"
    lore:
      - "品质：普通"
      - "耐久：<var:耐久>"
    耐久: "100~200"
    类型: "COW"