刷怪笼:
  动物刷怪笼:
    name: "<gold><bold>动物刷怪笼"
    lore:
      - "<aqua>品质：<yellow>普通"
      - "<aqua>刷怪次数：<yellow><var:刷怪次数>"
      - "<aqua>类型：<yellow><var:类型>"
    # 随机刷怪次数 50~100
    刷怪次数: "50~100"
    刷怪笼类型:
      # 所有动物的权重为 10
      - "Animals:10"
      # 猫的权重为 0，不会产生猫
      - "Cat:0"
  怪物刷怪笼:
    name: "<gold><bold>怪物刷怪笼"
    lore:
      - "<aqua>品质：<yellow>高级"
      - "<aqua>刷怪次数：<yellow><var:刷怪次数>"
      - "<aqua>类型：<yellow><var:类型>"
    刷怪次数: "100~500"
    刷怪笼类型:
      # 怪物的权重为 10
      - "Monster:10"

data:
  storage-method: h2